### ISSUE TITLE
Only yescrypt is accepted as hashing algorithm

### ISSUE THREAD

**Issue by fgierlinger** [ansible-lockdown/DEBIAN11-CIS#9]
**Describe the Issue**
The task "_Check debian11cis_grub_user password variable has been changed | if password blank or incorrect type and not being set_" in [tasks/main.yml](tasks/main.yml) checks if the password contains `$y$`. This prefix signifies a yescrypt hashed password. But the CIS hardening guide specifies, that either SHA512 or yescrypt are acceptable hashing algorithms.

https://github.com/ansible-lockdown/DEBIAN11-CIS/blob/e2b418df1ef701ebc6ef7760ea20a0dea090ad1d/tasks/main.yml#L69-L75

**Expected Behavior**
All hashing algorithms stated in the hardening guide should be accepted. The task should check for either a `$6$` prefix (SHA-512) or a `$y$` prefix (yescrypt).

**Actual Behavior**
Only yescrypt is accepted as hashing algorithm.

**Control(s) Affected**
5.4.1.4 Ensure strong password hashing algorithm is configured (Automated)

**Environment (please complete the following information):**

- branch being used: devel
- Ansible Version: 2.15.12
- Host Python Version: Python 3.9.6
- Ansible Server Python Version: Python 3.9.2

**Comment by uk-bolly** [comment]
hi @fgierlinger 

Thank you for taking the time to highlight this issue. I am raising a PR which should fix this issue and hope to get merged into devel asap.

Many thanks

uk-bolly

**Comment by uk-bolly** [comment]
hi @fgierlinger 

Thank you again for your time regarding this issue. You should find that this fix was merged into devel and is now in the main branch. I will close this issue, please feel free to reopen if this is not resolved as expected.

Many thanks

uk-bolly
